// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace MyGameplayTags
{
	/** Input Tags **/
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipWeapon);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquipWeapon);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);

	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);

	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);

	/** Player Tags **/
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UnEquip_Axe);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_TargetLock);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);

	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquip_Axe);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessfulBlock);

	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_TargetLock);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);

	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	/** Enemy Tags **/
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnBlockAble);

	/** Shared Tags **/
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SpawnProjectile);


	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);

	/** GameData Tags **/
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_Level_SurvivalGameModeMap);
	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_Level_MainMenuMap);

	GASPRE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_SaveGame_Slot_1);

}
